### ISSUE TITLE
[bug] Doesn't obey columns and lines

### ISSUE THREAD

**Issue by fleurc** [laymoth/wofi#1]
Really loved the theme and applied it. However i noticed a problem when i applied Macchiato Green, it seems that some part of the configuration (dk if padding, border or margins) squishes the columns and lines.

Setting 3 columns when there is not height or width set will show 2 columns until there is a width of at least 1200px. Setting height to solve the issue of lines doesn't work when columns are set, lines will always show 1 less than specified while cutting the text and image of the last option in half. (Example with 10 lines and 3 columns).

Idk what causes this but i wanted to warn about it.

**Comment by laymoth** [comment]
Can you give me the screenshot?

**Comment by fleurc** [comment]
Here is what happens when Width and Height are not specified over 1200x600 with the Macchiato Green theme on:
Columns being cut off. From the 3 specified columns only 2 appear.

[https://files.catbox.moe/kbyfju.png](https://files.catbox.moe/kbyfju.png)

Here is what happens when the Width and Height are specified over 1200x600 with the Macchiato Green theme on:
The columns stop being cut off, showing 3 out of the 3, but leaving some empty space on the sides.

[https://files.catbox.moe/5urqmq.png](https://files.catbox.moe/5urqmq.png)

No matter with what configuration, 1 line is always completely cut off and its previous line will only half-show. Example in pic 1 being specified 10 lines, only 9 get shown with the 9th being cut in half; In pic 2 out of the 11 specified, only 10 are shown with the 10th being cut in half.

**Comment by laymoth** [comment]
Can't access the website, but I'll try it myself after reinstall my Arch.

Anyway, thanks for the information :)

**Comment by fleurc** [comment]
Sorry, hadn't found a way to just plop the images on github, knowing now where and how to do that i will just post it here.

Image 1:
![kbyfju](https://github.com/laymoth/wofi/assets/35513885/58704c77-9d35-4038-83c0-edd1e50c580b)

Image 2:
![5urqmq](https://github.com/laymoth/wofi/assets/35513885/e652a3e0-d27e-412c-a28f-9f252662741f)

These are in the order mentioned on my previous comment.

**Comment by laymoth** [comment]
Apologies for the delay, @someone. As far as I have tested, I haven't been able to fix the issue with the number of lines. I've tested other themes like Arc-dark and Dracula, and they also show only 9 lines. However, I've managed to successfully adjust the column display. You can try modifying the padding value in the `#text` section to either `2` or `0`.

Code:
```
/* Macchiato Green */
@define-color accent #a6da95;
@define-color txt #cad3f5;
@define-color bg #24273a;
@define-color bg2 #494d64;

 * {
    font-family: 'JetBrains Mono Nerd Font', monospace;
    font-size: 14px;
 }

 /* Window */
 window {
    margin: 0px;
    border: 3px solid @accent;
    border-radius: 7px;
    background-color: @bg;
    animation: slideIn 0.5s ease-in-out both;
 }

 /* Slide In */
 @keyframes slideIn {
    0% {
       opacity: 0;
    }

    100% {
       opacity: 1;
    }
 }

 /* Inner Box */
 #inner-box {
    margin: 5px;
    padding: 5px;
    background-color: @bg;
    animation: fadeIn 0.5s ease-in-out both;
 }
 
 #inner-box > * {
   width: calc(100% / 3 - 10px); /* Adjust the value as needed */
   margin: 5px;
}


 /* Fade In */
 @keyframes fadeIn {
    0% {
       opacity: 0;
    }

    100% {
       opacity: 1;
    }
 }

 /* Outer Box */
 #outer-box {
    margin: 5px;
    padding: 10px;
    border: none;
    background-color: @bg;
 }

 /* Scroll */
 #scroll {
   max-height: calc(14px * 10 + 10px + 14px); /* Adjust the value as needed */
   overflow: auto;
}



 /* Input */
 #input {
    margin: 5px;
    padding: 10px;
    border: none;
    color: @accent;
    background-color: @bg2;
    animation: fadeIn 0.5s ease-in-out both;
 }

 /* Text */
 #text {
    margin: 5px;
    padding: 2px;
    color: @txt;
    animation: fadeIn 0.5s ease-in-out both;
 }

 /* Selected Entry */
 #entry:selected {
   background-color: @accent;
   border-radius: 7px;
 }

 #entry:selected #text {
    color: @bg;
 }
```

Here's the screenshots:
![2023-07-18T19:34:36,055170563+07:00](https://github.com/laymoth/wofi/assets/22806461/274efecc-0ada-4440-bcfc-fe4b7e951dfe)
![2023-07-18T19:30:04,530095435+07:00](https://github.com/laymoth/wofi/assets/22806461/b372392c-a4dc-4131-b379-d2837a0eadf1)
![2023-07-18T19:30:37,562338556+07:00](https://github.com/laymoth/wofi/assets/22806461/a79745a9-00a2-4c26-91f8-639b983ef3b9)

**Comment by laymoth** [comment]
Apologies for the delay, @fleurc 

As far as I have tested, I haven't been able to fix the issue with the number of lines. I've tested other themes like Arc-dark and Dracula, and they also show only 9 lines. However, I've managed to successfully adjust the column display. You can try modifying the padding value in the `#text` section to either `2` or `0`.

Code:
```
/* Macchiato Green */
@define-color accent #a6da95;
@define-color txt #cad3f5;
@define-color bg #24273a;
@define-color bg2 #494d64;

 * {
    font-family: 'JetBrains Mono Nerd Font', monospace;
    font-size: 14px;
 }

 /* Window */
 window {
    margin: 0px;
    border: 3px solid @accent;
    border-radius: 7px;
    background-color: @bg;
    animation: slideIn 0.5s ease-in-out both;
 }

 /* Slide In */
 @keyframes slideIn {
    0% {
       opacity: 0;
    }

    100% {
       opacity: 1;
    }
 }

 /* Inner Box */
 #inner-box {
    margin: 5px;
    padding: 5px;
    background-color: @bg;
    animation: fadeIn 0.5s ease-in-out both;
 }
 
 #inner-box > * {
   width: calc(100% / 3 - 10px); /* Adjust the value as needed */
   margin: 5px;
}


 /* Fade In */
 @keyframes fadeIn {
    0% {
       opacity: 0;
    }

    100% {
       opacity: 1;
    }
 }

 /* Outer Box */
 #outer-box {
    margin: 5px;
    padding: 10px;
    border: none;
    background-color: @bg;
 }

 /* Scroll */
 #scroll {
   max-height: calc(14px * 10 + 10px + 14px); /* Adjust the value as needed */
   overflow: auto;
}



 /* Input */
 #input {
    margin: 5px;
    padding: 10px;
    border: none;
    color: @accent;
    background-color: @bg2;
    animation: fadeIn 0.5s ease-in-out both;
 }

 /* Text */
 #text {
    margin: 5px;
    padding: 2px;
    color: @txt;
    animation: fadeIn 0.5s ease-in-out both;
 }

 /* Selected Entry */
 #entry:selected {
   background-color: @accent;
   border-radius: 7px;
 }

 #entry:selected #text {
    color: @bg;
 }
```

Here's the screenshots:
![2023-07-18T19:34:36,055170563+07:00](https://github.com/laymoth/wofi/assets/22806461/274efecc-0ada-4440-bcfc-fe4b7e951dfe)
![2023-07-18T19:30:04,530095435+07:00](https://github.com/laymoth/wofi/assets/22806461/b372392c-a4dc-4131-b379-d2837a0eadf1)
![2023-07-18T19:30:37,562338556+07:00](https://github.com/laymoth/wofi/assets/22806461/a79745a9-00a2-4c26-91f8-639b983ef3b9)

**Comment by fleurc** [comment]
Thank you very much! I will try this soon. I just did a system switch into OpenMandriva which uses KDE but i have Sway installed and just need to put my config back together. Will be trying this as soon as i can

**Comment by fleurc** [comment]
It worked wonderfully, now there remains only the issue of lines, but as you said it seems to be a problem with Wofi and not the themes themselves.

**Comment by laymoth** [comment]
I will close this issue, thank you for using this theme!
